// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Week_13_Assignment.Models;

namespace Week_13_Assignment.Data
{
    public partial class Week_13_AssignmentContext : DbContext
    {
        public Week_13_AssignmentContext()
        {
        }

        public Week_13_AssignmentContext(DbContextOptions<Week_13_AssignmentContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<FacultyClass> FacultyClasses { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentSchedule> StudentSchedules { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Class>(entity =>
            {
                entity.Property(e => e.ClassId).HasColumnName("ClassID");

                entity.Property(e => e.ClassRoomNumber)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.StartDate).HasColumnType("date");

                entity.Property(e => e.SubjectId).HasColumnName("SubjectID");

                entity.HasOne(d => d.Subject)
                    .WithMany(p => p.Classes)
                    .HasForeignKey(d => d.SubjectId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Classes__Subject__7C4F7684");
            });

            modelBuilder.Entity<Faculty>(entity =>
            {
                entity.ToTable("Faculty");

                entity.Property(e => e.FacultyId).HasColumnName("FacultyID");

                entity.Property(e => e.FacFirstName)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.FacLastName)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.Property(e => e.TenureIsChecked).HasColumnName("Tenure_is_checked");

                entity.Property(e => e.Title)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false);
            });

            modelBuilder.Entity<FacultyClass>(entity =>
            {
                entity.HasKey(e => e.FacultyClassesId)
                    .HasName("PK__Faculty___3192B6071D3A44FE");

                entity.ToTable("Faculty_Classes");

                entity.Property(e => e.FacultyClassesId).HasColumnName("Faculty_ClassesID");

                entity.Property(e => e.ClassId).HasColumnName("ClassID");

                entity.Property(e => e.FacultyId).HasColumnName("FacultyID");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.FacultyClasses)
                    .HasForeignKey(d => d.ClassId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Faculty_C__Class__7F2BE32F");

                entity.HasOne(d => d.Faculty)
                    .WithMany(p => p.FacultyClasses)
                    .HasForeignKey(d => d.FacultyId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Faculty_C__Facul__00200768");
            });

            modelBuilder.Entity<Student>(entity =>
            {
                entity.Property(e => e.StudFirstName)
                    .IsRequired()
                    .HasMaxLength(128);

                entity.Property(e => e.StudLastName)
                    .IsRequired()
                    .HasMaxLength(128);

                entity.Property(e => e.StudMajor)
                    .IsRequired()
                    .HasMaxLength(128);

                entity.Property(e => e.StudPhone)
                    .IsRequired()
                    .HasMaxLength(14);
            });

            modelBuilder.Entity<StudentSchedule>(entity =>
            {
                entity.HasKey(e => e.ScheduleId)
                    .HasName("PK__Student___3214EC272EF28889");

                entity.ToTable("Student_Schedules");

                entity.Property(e => e.ScheduleId).HasColumnName("ScheduleID");

                entity.Property(e => e.ClassId).HasColumnName("ClassID");

                entity.Property(e => e.Grade)
                    .IsRequired()
                    .HasMaxLength(1)
                    .IsUnicode(false);

                entity.Property(e => e.StudentId).HasColumnName("StudentID");

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.StudentSchedules)
                    .HasForeignKey(d => d.ClassId)
                    .HasConstraintName("FK__Student_S__Class__7E37BEF6");

                entity.HasOne(d => d.Student)
                    .WithMany(p => p.StudentSchedules)
                    .HasForeignKey(d => d.StudentId)
                    .HasConstraintName("FK__Student_S__Stude__7D439ABD");
            });

            modelBuilder.Entity<Subject>(entity =>
            {
                entity.Property(e => e.SubjectId).HasColumnName("SubjectID");

                entity.Property(e => e.ClassId).HasColumnName("ClassID");

                entity.Property(e => e.SubjectCode)
                    .HasMaxLength(20)
                    .IsUnicode(false);

                entity.Property(e => e.SubjectDescriptions)
                    .HasMaxLength(255)
                    .IsUnicode(false);

                entity.Property(e => e.SubjectName)
                    .HasMaxLength(50)
                    .IsUnicode(false);

                entity.HasOne(d => d.Class)
                    .WithMany(p => p.Subjects)
                    .HasForeignKey(d => d.ClassId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__Subjects__ClassI__797309D9");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}