// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Week_13_Assignment.Models
{
    public partial class FacultyClass
    {
        public int FacultyClassesId { get; set; }
        public int ClassId { get; set; }
        public int FacultyId { get; set; }

        public virtual Class Class { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}